title: Reboot 3 Times
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: 'https://oops.r3t.io'
params:
  alwaysKeepBrandColor: true
  brand: '#0a0c0f'
  categories:
    - description: All the important things.
      name: Colorado
  customTabs:
    - link: 'https://stats.uptimerobot.com/VJp6qUxWD6'
      name: Status
    - link: 'https://blog.r3t.io'
      name: Ghost
    - link: 'https://cr.r3t.io'
      name: Harbor
    - link: 'https://git.r3t.io'
      name: Gitea
  dateFormat: 'January 2, 2006 at 3:04 PM'
  description: Is this shit down? Maybe.
  disableDarkMode: false
  disrupted: '#cc4400'
  down: '#e60000'
  googleAnalytics: UA-00000000-1
  incidentHistoryFormat: yearly
  incidentPostsPerPage: 10
  logo: /logo.png
  notice: '#24478f'
  ok: '#008000'
  shortDateFormat: '15:04 — Jan 2'
  systems:
    - category: Colorado
      name: Broomfield
  useLargeHeaderDesign: false
  useLogo: false
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  home:
    - html
    - json
    - rss
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
